insert into metrics ( name, description)
values ('Finance Net New ARR','NetNewARR'),
('Finance Gross New ARR','GrossNewARR'),
('Finance Cancellations ARR','Cancellations ARR'),
('Finance Renewal@FP ARR','Renewal@FPARR'),
('Discover Marketable Universe','MarketableUniverse'),
('Discover Traffic','Traffic'),
('Discover UQFM Conversion','UQFMConversion'),
('Discover Paid Media Spend','Paid Media Spend'),
('Paid Media Sourced UQFMs','Paid Media Sourced UQFMs'),
('Bounce Rate', 'Bounce Rate'),
('New UQFMs', 'Try New UQFMs'),
('Cumulative UQFMS', 'Try Cumulative UQFMS'),
('New QFMs', 'New QFMs'),
('Cumulative QFMs', 'Try Cumulative QFMs'),
('28 Day New UQFM to QFM', 'Try 28 Day New UQFM to QFM'),
('Cum. UQFM to QFM', 'Try Cum. UQFM to QFM'),

('Gross New ARR', 'Buy Gross New ARR'),
('Gross New Subs', 'Buy Gross New Units'),
('Conversion', 'Buy Conversion'),
('LTV ROI', 'Life Time Value Return on Investment'),
('PM Spend - Buy', 'Buy Paid Media Spend'),
('Marketing Sourced ARR', 'Buy Marketing Sourced ARR'),

('% Activated', 'Use % Activated'),
('Wk 4 WAU Rate', 'Use Wk 4 WAU Rate'),
('Month 1 Return Rate', 'Use Month 1 Return Rate'),
('Low CEI', 'Use Low CEI'),
('Medium CEI', 'Use Medium CEI'),
('High CEI', 'Use High CEI'),
('0 (Inactive) CEI', 'Use 0 (Inactive) CEI'),
('Repeat User MAU', 'Use Repeat User MAU'),

('Cancellations ARR', 'Renew Cancellations ARR'),
('Cancellations ARR', 'Renew Cancellations ARR'),
('QTR Fin Retention Rate', 'Renew QTR Fin Retention Rate'),
('QTR UI Rate', 'Renew QTR UI Rate'),
('QTR PF Rate', 'Renew QTR PF Rate'),
('Cancellations ARR', 'Renew Cancellations ARR'),
('EOT Retention Rate', 'Renew EOT Retention Rate'),
('QTR Fin Retention Rate', 'Renew QTR Fin Retention Rate')




insert into metrics ( name, description)
values('Finance Net New ARR'	,'NetNewARR'),
('Finance Gross New ARR',	'GrossNewARR'),
('Finance Cancellations ARR','Cancellations ARR'),
('Finance Renewal@FP ARR','Renewal@FPARR'),
('Discover Marketable Universe','MarketableUniverse'),
('Discover Traffic','Traffic'),
('Discover UQFM Conversion','UQFMConversion'),
('Discover Paid Media Spend','Paid Media Spend'),
('Paid Media Sourced UQFMs','Paid Media Sourced UQFMs'),
('Bounce Rate','Bounce Rate'),
('New UQFMs','Try New UQFMs'),
('Cumulative UQFMS','Try Cumulative UQFMS'),
('New QFMs','New QFMs'),
('Cumulative QFMs','Try Cumulative QFMs'),
('28 Day New UQFM to QFM','Try 28 Day New UQFM to QFM'),
('Cum. UQFM to QFM','Try Cum. UQFM to QFM'),
('Gross New ARR','Buy Gross New ARR'),
('Gross New Subs','Buy Gross New Units'),
('Conversion','	Buy Conversion'),
('PM Spend - Buy','Buy Paid Media Spend'),
('Marketing Sourced ARR','Buy Marketing Sourced ARR'),
('%Paid User Sucess - Download','Use Paid User Success'),
('%Paid User Sucess - Launches','Use Paid User Success'),
('WK 0 WAU rate','Use WK 0 WAU rate'),
('Wk 4 WAU Rate','Use Wk 4 WAU Rate'),
('Engagement Index','Use Engagement Index'),
('Paid User MAU','Use Paid User MAU'),
('Repeat User MAU','Use Repeat User MAU'),
('Cancellations ARR','Renew Cancellations ARR'),
('Cancellations ARR','Renew Cancellations ARR'),
('QTR Fin Retention Rate','Renew QTR Fin Retention Rate'),
('QTR UI Rate','Renew QTR UI Rate'),
('QTR PF Rate','Renew QTR PF Rate'),
('Cancellations ARR','Renew Cancellations ARR'),
('EOT Retention Rate','Renew EOT Retention Rate'),
('QTR Fin Retention Rate','Renew QTR Fin Retention Rate'),
