insert into metrics ( name, description)
values ('Finance Net New ARR','NetNewARR'),
('Finance Gross New ARR','GrossNewARR'),
('Finance Cancellations ARR','Cancellations ARR'),
('Finance Renewal@FP ARR','Renewal@FPARR'),
('Discover Marketable Universe','MarketableUniverse'),
('Discover Traffic','Traffic'),
('Discover UQFM Conversion','UQFMConversion'),
('Discover Paid Media Spend','Paid Media Spend'),
('Paid Media Sourced UQFMs','Paid Media Sourced UQFMs'),
('Bounce Rate', 'Bounce Rate'),
('New UQFMs', 'Try New UQFMs'),
('Cumulative UQFMS', 'Try Cumulative UQFMS'),
('New QFMs', 'New QFMs'),
('Cumulative QFMs', 'Try Cumulative QFMs'),
('28 Day New UQFM to QFM', 'Try 28 Day New UQFM to QFM'),
('Cum. UQFM to QFM', 'Try Cum. UQFM to QFM'),
('Paid Media Spend', 'Buy Paid Media Spend'),
('Marketing Sourced ARR', 'Buy Marketing Sourced ARR'),
('Conversion', 'Buy Conversion'),
('Gross New ARR', 'Buy Gross New ARR'),
('Gross New Units', 'Buy Gross New Units'),
('Engagement Index', 'Use Engagement Index'),
('Paid User MAU', 'Use Paid User MAU'),
('Repeat User MAU', 'Use Repeat User MAU'),
('Paid User Success', 'Use Paid User Success'),
('WK 0 WAU rate', 'Use WK 0 WAU rate'),
('Wk 4 WAU Rate', 'Use Wk 4 WAU Rate'),
('Cancellations ARR', 'Renew Cancellations ARR'),
('Cancellations ARR', 'Renew Cancellations ARR'),
('QTR Fin Retention Rate', 'Renew QTR Fin Retention Rate'),
('QTR UI Rate', 'Renew QTR UI Rate'),
('QTR PF Rate', 'Renew QTR PF Rate'),
('Cancellations ARR', 'Renew Cancellations ARR'),
('EOT Retention Rate', 'Renew EOT Retention Rate'),
('QTR Fin Retention Rate', 'Renew QTR Fin Retention Rate')




