/** Query Filter Groups **/
-- G1 = PAid Media Spend
-- G2 = Marketable Universe, UQFM Conversion, Paid Media Sourced UQFMS, New UQFMs, New QFMS, 
        -- Cumulative QFMS, Cumulative UQFMS, 28 Day New , Cum UQFM to QFM, In Product NPS, 
        -- Engagement Index, Paid User MAU, % Paid User Success, WK 0 WAU Rate, Wk 4WAU Rate, %Learn Discovery
        -- In Product NPS , New QFMs, 28DayNewUQFMtoQFM, CumUQFM to QFM, Cumulative QFMS, Cumulative UQFMS, 
-- G5 = Bounce Rate, Conversion,   Repeat User MAU, Traffic, 
-- G6 = F2P  Conversion
-- G9 = Marketing Sourced ARR, D2P Conversion

/*********************************************************************************************/
/**************************************Queries************************************************/
/*********************************************************************************************/

--JourneyG1ARR : PAid Media Spend
SELECT channel,
         geo_code ,
         market_area_code ,		 
		case 	when market_area_code = 'US' then 'US' 
					when market_area_code = 'UK' then 'UK'
					when market_area_code = 'GER' then 'GER'
					when market_area_code = 'ANZ' then 'ANZ'
					when market_area_code = 'JPN' then 'JPN'
					else 'ROW'
		end as market_area_group,
         product_name ,
         quarter,
         route_to_market ,
         segment_pivot ,
         signup_category ,
         subscription_offering ,
         visit_type ,
         week,
         sum(paid_media_spend_actual) AS PaidMediaSpendActual,
         sum(paid_media_spend_cw) AS PaidMediaSpendCW,
         sum(paid_media_spend_lq) AS PaidMediaSpendLQ,
         sum(paid_media_spend_lw) AS PaidMediaSpendLW,
         sum(paid_media_spend_lylq) AS PaidMediaSpendLYLQ,
         sum(paid_media_spend_ly) AS PaidMediaSpendLY,
         sum(paid_media_spend_target_cw) AS PaidMediaSpendTargetCW ,
         sum(paid_media_spend_target_fq) AS PaidMediaSpendTargetFQ,
         sum(paid_media_spend_target) AS PaidMediaSpendTarget,
		 (sum(paid_media_spend_actual) - sum(paid_media_spend_lylq) )/ nullIf(sum(paid_media_spend_lylq),0) as PaidMediaSpendQQLY,
		 (sum(paid_media_spend_actual) - sum(paid_media_spend_lq) )/ nullIf(sum(paid_media_spend_lq),0) as PaidMediaSpendQQTY,
		 (sum(paid_media_spend_actual) - sum(paid_media_spend_target)) / nullIf(sum(paid_media_spend_target),0) as PaidMediaSpendVsQrf,
		 (sum(paid_media_spend_cw) - sum(paid_media_spend_target_cw)) / nullIf(sum(paid_media_spend_target_cw),0) as PaidMediaSpendVsQrfCW,
		 (sum(paid_media_spend_cw) - sum(paid_media_spend_lw) )/ nullIf(sum(paid_media_spend_lw),0) as PaidMediaSpendWW,
		 (sum(paid_media_spend_actual) - sum(paid_media_spend_ly)) / nullIf(sum(paid_media_spend_ly),0) as PaidMediaSpendYY,
		sum(paid_media_spend_actual) - sum(paid_media_spend_target) as PaidMediaSpendVsQrfDiff,
		sum(paid_media_spend_cw) - sum(paid_media_spend_target_cw) as PaidMediaSpendVsQrfDiffCW
FROM newJourn
GROUP BY  channel, geo_code ,market_area_code ,
		case 	when market_area_code = 'US' then 'US' 
					when market_area_code = 'UK' then 'UK'
					when market_area_code = 'GER' then 'GER'
					when market_area_code = 'ANZ' then 'ANZ'
					when market_area_code = 'JPN' then 'JPN'
					else 'ROW'
		end, product_name ,quarter,route_to_market ,segment_pivot , signup_category , subscription_offering ,visit_type ,week

--JourneyG2ARR : Marketable Universe, UQFM Conversion, Paid Media Sourced UQFMS, New UQFMs, New QFMS, 
        -- Cumulative QFMS, Cumulative UQFMS, 28 Day New , Cum UQFM to QFM, In Product NPS, 
        -- Engagement Index, Paid User MAU, % Paid User Success, WK 0 WAU Rate, Wk 4WAU Rate, %Learn Discovery
        -- In Product NPS , New QFMs, 28DayNewUQFMtoQFM, CumUQFM to QFM, Cumulative QFMS, Cumulative UQFMS,
SELECT channel,
         geo_code ,
         market_area_code ,
		case 	when market_area_code = 'US' then 'US' 
					when market_area_code = 'UK' then 'UK'
					when market_area_code = 'GER' then 'GER'
					when market_area_code = 'ANZ' then 'ANZ'
					when market_area_code = 'JPN' then 'JPN'
					else 'ROW'
		end as market_area_group,
         product_name ,
         quarter,
         route_to_market ,
         segment_pivot ,
         signup_category ,
         subscription_offering ,
         visit_type ,
         week,
		 /**In Product NPS TODO: GET DATA AND USE HERE**/
        sum(uqfm_denom_actual) AS UQFMDenomActual ,
         sum(uqfm_denom_cw) AS UQFMDenomCW,
         sum(uqfm_denom_lq) AS UQFMDenomLQ,
         sum(uqfm_denom_lw) AS UQFMDenomLW,
         sum(uqfm_denom_lylq) AS UQFMDenomLYLQ,
         sum(uqfm_denom_ly) AS UQFMDenomLY,
         sum(uqfm_nom_actual) AS UQFMNOMActual,
         sum(uqfm_nom_cw) AS UQFMNOMCW,
         sum(uqfm_nom_lq) AS UQFMNOMLQ,
         sum(uqfm_nom_lw) AS UQFMNOMLW,
         sum(uqfm_nom_lylq) AS UQFMNOMLYLQ,
         sum(uqfm_nom_ly) AS UQFMNOMLY,
		 /** 28 Day New UQFM to QFM **/
         sum(bounce_rate_base_actual)/ sum(nullIf(entries_actual,
        0)) AS Day28NewUQFMActual,
         sum([28day_new_uqfm_to_qfm_base_actual]) AS Day28NewUQFMBaseActual ,
         sum([28day_new_uqfm_to_qfm_base_cw]) AS Day28NewUQFMBaseCW ,
         sum([28day_new_uqfm_to_qfm_base_lq]) AS Day28NewUQFMBaseLQ ,
         sum([28day_new_uqfm_to_qfm_base_lw]) AS Day28NewUQFMBaseLW ,
         sum([28day_new_uqfm_to_qfm_base_lylq]) AS Day28NewUQFMBaseLYLQ ,
         sum([28day_new_uqfm_to_qfm_base_ly]) AS Day28NewUQFMBaseLY,
         sum([28day_new_uqfm_to_qfm_base_target_cw]) AS Day28NewUQFMBaseTargetCW ,
         sum([28day_new_uqfm_to_qfm_base_target_fq]) AS Day28NewUQFMBaseTargetFQ ,
         sum([28day_new_uqfm_to_qfm_base_target]) AS Day28NewUQFMBaseTarget ,
         sum([28day_new_uqfm_to_qfm_base_cw]) / nullIf(sum(new_uqfms_cw),
        0) AS Day28NewUQFMCW,
         sum([28day_new_uqfm_to_qfm_base_lq])/ nullIf(sum(new_uqfms_lq),
        0) AS Day28NewUQFMLQ,
         sum([28day_new_uqfm_to_qfm_base_lw]) /nullIf(sum(new_uqfms_lw),
        0) AS Day28NewUQFMLW,
         sum([28day_new_uqfm_to_qfm_base_ly]) / nullIf(sum(new_uqfms_ly),
        0) AS Day28NewUQFMLY,
         sum([28day_new_uqfm_to_qfm_base_lylq]) / nullIf(sum(new_uqfms_lylq) ,
        0) AS Day28NewUQFMLYLQ,
         sum([28day_new_uqfm_to_qfm_base_target]) / nullIf(sum(new_uqfms_target),
        0) AS Day28NewUQFMTarget,
         sum([28day_new_uqfm_to_qfm_base_target_cw]) / nullIf(sum(new_uqfms_target_cw),
        0)as Day28NewUQFMTargetCW,
         sum([28day_new_uqfm_to_qfm_base_target_fq]) /nullIf(sum(new_uqfms_target_fq),
        0)as Day28NewUQFMTargetFQ,
         
		/** Cum UQFM To QFM Conversion **/
         sum(cumulative_uqfms_actual) / nullIf(sum(new_uqfms_actual),
        0) AS CumulativeUqfmToQFMActual,
         sum(cumulative_uqfms_actual) AS CumulativeUqfmToQFMCW,
         sum(cumulative_uqfms_lq)/ nullIf(sum(new_qfms_lq),
        0) AS CumulativeUqfmToQFMLQ,
         sum(new_qfms_lw) AS CumulativeUqfmToQFMLW,
         sum(cumulative_uqfms_ly)/ nullIf(sum(new_qfms_ly),
        0) AS CumulativeUqfmToQFMLY,
         sum(cumulative_uqfms_lylq)/ nullIf(sum(new_qfms_lylq),
        0) AS CumulativeUqfmToQFMLYLQ,
         sum(cumulative_uqfms_target_cw)/ nullIf(sum(new_qfms_target_cw),
        0) AS CumulativeUqfmToQFMTargetCW,
         sum(cumulative_uqfms_target_fq)/ nullIf(sum(new_qfms_target_fq),
        0) AS CumulativeUqfmToQFMTargetFQ,
         sum(cumulative_uqfms_target)/ nullIf(sum(new_qfms_target),
        0) AS CumulativeUqfmToQFMTarget,
		/** Cumulative QFMs **/
         sum(cumulative_qfms_actual) AS CumulativeQFMSActual,
         sum(cumulative_qfms_lq) AS CumulativeQFMSLQ,
         sum(cumulative_qfms_lylq) AS CumulativeQFMSLYLQ,
         sum(cumulative_qfms_ly) AS CumulativeQFMSLY,
         sum(cumulative_qfms_target_cw) AS CumulativeQFMSTargetCW,
         sum(cumulative_qfms_target_fq) AS CumulativeQFMSTargetFQ,
         sum(cumulative_qfms_target) AS CumulativeQFMSTarget,
         sum(cumulative_qfms_actual) / nullIf(sum(cumulative_qfms_lylq),
        0) AS CumulativeQFMSQQLY,
         sum(cumulative_qfms_actual) / nullIf(sum(cumulative_qfms_lq),
        0) AS CumulativeQFMSQQTY,
         sum(cumulative_qfms_actual) -sum(cumulative_qfms_target) / nullIf(sum(cumulative_qfms_target),
        0) AS CumulativeQFMSVsQrf,
		/** Cumulative UQFMS**/
         sum(cumulative_uqfms_actual) AS CumulativeUqfmsActual,
         sum(cumulative_uqfms_lq) AS CumulativeUqfmsLQ,
         sum(cumulative_uqfms_lylq) AS CumulativeUqfmsLYLQ,
         sum(cumulative_uqfms_ly) AS CumulativeUqfmsLY,
         sum(cumulative_uqfms_target_cw) AS CumulativeUqfmsTargetCW,
         sum(cumulative_uqfms_target_fq) AS CumulativeUqfmsTargetFQ,
         sum(cumulative_uqfms_target) AS CumulativeUqfmsTarget,
		 /**Marketable Universe**/
         sum(marketable_universe_actual) AS MarketableUniverseActual,
         sum(marketable_universe_cw) AS MarketableUniverseCW,
         sum(marketable_universe_lq) AS MarketableUniverseLQ,
         sum(marketable_universe_lw) AS MarketableUniverseLW,
         sum(marketable_universe_lylq) AS MarketableUniverseLYLQ,
         sum(marketable_universe_ly) AS MarketableUniverseLY,
         sum(marketable_universe_target_cw) AS MarketableUniverseTargetCW,
         sum(marketable_universe_target_fq) AS MarketableUniverseTargetFQ ,
         sum(marketable_universe_target) AS MarketableUniverseTarget,
         sum(marketable_universe_vs_qrf_cw) AS MarketableUniverseVsQrfDiffCW,
         sum(marketable_universe_vs_qrf_diff) AS MarketableUniverseVsQrfDiff,
         (sum(marketable_universe_actual)- sum(marketable_universe_lylq)) /nullIf(sum(marketable_universe_lylq),
        0) AS MarketableUniverseQQLY,
         (sum(marketable_universe_actual)- sum(marketable_universe_lq)) /nullIf(sum(marketable_universe_lq),
        0)as MarketableUniverseQQTY,
         (sum(marketable_universe_actual)- sum(marketable_universe_target)) /nullIf(sum(marketable_universe_target),
        0)as MarketableUniverseVsQrf,
         (sum(marketable_universe_cw)- sum(marketable_universe_target_cw) )/nullIf(sum(marketable_universe_target_cw),
        0)as MarketableUniverseVsQrfCW,
         (sum(marketable_universe_cw)- sum(marketable_universe_lw) )/nullIf(sum(marketable_universe_lw),
        0)as MarketableUniverseWW,
         (sum(marketable_universe_actual)- sum(marketable_universe_ly) )/nullIf(sum(marketable_universe_ly),
        0)as MarketableUniverseYY,
        /**New QFM**/
            sum(new_qfms_actual) AS NewQFMSActual,
         sum(new_qfms_cw) AS NewQFMSCW,
         sum(new_qfms_lq) AS NewQFMSLQ,
         sum(new_qfms_lw) AS NewQFMSLW,
         sum(new_qfms_lylq) AS NewQFMSLYLQ,
         sum(new_qfms_ly) AS NewQFMSLY,
         sum(new_qfms_target_cw) AS NewQFMSTargetCW,
         sum(new_qfms_target_fq) AS NewQFMSTargetFQ,
         sum(new_qfms_target) AS NewQFMSTarget,
         sum(new_qfms_vs_qrf_cw_diff) AS NewQFMSVsQrfDiffCW,
         sum(new_qfms_vs_qrf_diff) AS NewQFMSVsQrfDiff,
		/** New UQFMS**/
         sum(new_uqfms_actual) AS NewUQFMSActual,
         sum(new_uqfms_cw) AS NewUQFMSCW,
         sum(new_uqfms_lq) AS NewUQFMSLQ,
         sum(new_uqfms_lw) AS NewUQFMSLW,
         sum(new_uqfms_lylq) AS NewUQFMSLYLQ,
         sum(new_uqfms_ly) AS NewUQFMSLY,
         sum(new_uqfms_target_cw) AS NewUQFMSTargetCW,
         sum(new_uqfms_target_fq) AS NewUQFMSTargetFQ ,
         sum(new_uqfms_target) AS NewUQFMSTarget,
         (sum(new_uqfms_actual) - sum(new_uqfms_lylq)) / nullIf(sum(new_uqfms_lylq),
        0) AS NewUQFMSQQLY,
         (sum(new_uqfms_actual) - sum(new_uqfms_lq)) / nullIf(sum(new_uqfms_lq),
        0) AS NewUQFMSQQTY,
         (sum(new_uqfms_actual) - sum(new_uqfms_target)) / nullIf(sum(new_uqfms_target),
        0) AS NewUQFMSVsQRF,
         (sum(new_uqfms_cw) - sum(new_uqfms_target_cw)) / nullIf(sum(new_uqfms_target_cw),
        0) AS NewUQFMSVsQRFCW,
         sum(new_uqfms_actual) - sum(new_uqfms_target) AS NewUQFMSQRFDiff,
         (sum(new_uqfms_cw) - sum(new_uqfms_target_cw)) / nullIf(sum(new_uqfms_target_cw),
        0)as NewUQFMSQRFDiffCW,
         (sum(new_uqfms_cw) - sum(new_uqfms_lw) )/ nullIf(sum(new_uqfms_lw),
        0)as NewUQFMSWW,
         (sum(new_uqfms_actual) - sum(new_uqfms_ly)) / nullIf(sum(new_uqfms_ly),
        0)as NewUQFMSYY,
		/** Paid Media Sourced UQFMS**/
         sum(paid_media_sourced_uqfms_actual) AS PaidMediaSourcedUQFMSActual,
         sum(paid_media_sourced_uqfms_cw) AS PaidMediaSourcedUQFMSCW,
         sum(paid_media_sourced_uqfms_lq) AS PaidMediaSourcedUQFMSLQ,
         sum(paid_media_sourced_uqfms_lw) AS PaidMediaSourcedUQFMSLW,
         sum(paid_media_sourced_uqfms_lylq) AS PaidMediaSourcedUQFMSLYLQ,
         sum(paid_media_sourced_uqfms_ly) AS PaidMediaSourcedUQFMSLY,
         sum(paid_media_sourced_uqfms_target_cw) AS PaidMediaSourcedUQFMSTargetCW,
         sum(paid_media_sourced_uqfms_target_fq) AS PaidMediaSourcedUQFMSTargetFQ ,
         sum(paid_media_sourced_uqfms_target) AS PaidMediaSourcedUQFMSTarget,
         (sum(paid_media_sourced_uqfms_actual) - sum(paid_media_sourced_uqfms_lylq) )/ nullIf(sum(paid_media_sourced_uqfms_lylq),
        0) AS PaidMediaSourcedUQFMSQQLY,
         (sum(paid_media_sourced_uqfms_actual) - sum(paid_media_sourced_uqfms_lq)) / nullIf(sum(paid_media_sourced_uqfms_lq),
        0) AS PaidMediaSourcedUQFMSQQTY,
         (sum(paid_media_sourced_uqfms_actual) - sum(paid_media_sourced_uqfms_target)) / nullIf(sum(paid_media_sourced_uqfms_target),
        0) AS PaidMediaSourcedUQFMSVsQRF,
         (sum(paid_media_sourced_uqfms_cw) - sum(paid_media_sourced_uqfms_target_cw)) / nullIf(sum(paid_media_sourced_uqfms_target_cw),
        0) AS PaidMediaSourcedUQFMSVsQRFCW,
         sum(paid_media_sourced_uqfms_actual) - sum(paid_media_sourced_uqfms_target) AS PaidMediaSourcedUQFMSQRFDiff,
         (sum(paid_media_sourced_uqfms_cw) - sum(paid_media_sourced_uqfms_target_cw)) / nullIf(sum(paid_media_sourced_uqfms_target_cw),
        0)as PaidMediaSourcedUQFMSQRFDiffCW,
         (sum(paid_media_sourced_uqfms_cw) - sum(paid_media_sourced_uqfms_lw)) / nullIf(sum(paid_media_sourced_uqfms_lw),
        0)as PaidMediaSourcedUQFMSWW,
         (sum(paid_media_sourced_uqfms_actual) - sum(paid_media_sourced_uqfms_ly)) / nullIf(sum(paid_media_sourced_uqfms_ly),
        0)as PaidMediaSourcedUQFMSYY,
		/** UQFM Conversion **/
         sum(uqfm_nom_actual) / nullIf(sum(uqfm_denom_actual),
        0) AS UQFMConversionActual,
         sum(uqfm_nom_cw) / nullIf(sum(uqfm_denom_cw),
        0) AS UQFMConversionCW,
         sum(uqfm_nom_lq) / nullIf(sum(uqfm_denom_lq),
        0) AS UQFMConversionLQ,
         sum(uqfm_nom_lw) / nullIf(sum(uqfm_denom_lw),
        0) AS UQFMConversionLW,
         sum(uqfm_nom_ly) / nullIf(sum(uqfm_denom_ly),
        0) AS UQFMConversionLY,
         sum(uqfm_nom_lylq) / nullIf(sum(uqfm_denom_lylq),
        0) AS UQFMConversionLYLQ,
         /** Learn Discovery % **/
         sum(learn_panel_30_days_actual) / nullIf(sum(total_paid_members_actual),
        0) AS LearnDiscoveryActual,
         --sum(learn_panel_30_days_lw) / nullIf(sum(total_paid_members_lw),        0) AS LearnDiscoveryLW,
         sum(learn_panel_30_days_ly) / nullIf(sum(total_paid_members_ly),
        0) AS LearnDiscoveryLY,
         sum(learn_panel_30_days_lq) / nullIf(sum(total_paid_members_lq),
        0) AS LearnDiscoveryLQ,
         --sum(learn_panel_30_days_cw) / nullIf(sum(total_paid_members_cw),        0) AS LearnDiscoveryCW,
         sum(learn_panel_30_days_lylq) / nullIf(sum(total_paid_members_lylq),
        0) AS LearnDiscoveryLYLQ,
		/** Paid User Success **/
         sum(paid_download_7_days_actual) / nullIf(sum(total_paid_members_actual),
        0) AS PaidUserSuccessActual,
         --sum(paid_download_7_days_lw) / nullIf(sum(total_paid_members_lw),        0) AS PaidUserSuccessLW,
         sum(paid_download_7_days_ly) / nullIf(sum(total_paid_members_ly),
        0) AS PaidUserSuccessLY,
         sum(paid_download_7_days_lq) / nullIf(sum(total_paid_members_lq),
        0) AS PaidUserSuccessLQ,
         sum(paid_download_7_days_lylq) / nullIf(sum(total_paid_members_lylq),
        0) AS PaidUserSuccessLYLQ,
         --sum(paid_download_7_days_cw) / nullIf(sum(total_paid_members_cw),        0) AS PaidUserSuccessCW 
		/** Engagement Index **/
		sum(engagement_index_actual) AS EngagementIndexActual,
         sum(engagement_index_base_cw) AS EngagementIndexCW,
         sum(engagement_index_lq) AS EngagementIndexLQ,
         sum(engagement_index_base_lw) AS EngagementIndexLW,
         sum(engagement_index_lylq) AS EngagementIndexLYLQ,
         sum(engagement_index_ly) AS EngagementIndexLY,
		 /** Paid User MAU**/
         sum(paid_mau_overall_actual) / nullIf(sum(cumulative_paid_members_actual),
        0) AS PaidUserMAUActual,
         sum(paid_mau_overall_cw) / nullIf(sum(cumulative_paid_members_cw),
        0) AS PaidUserMAUCW,
         sum(paid_mau_overall_lq)/ nullIf(sum(cumulative_paid_members_lq),
        0) AS PaidUserMAULQ,
         sum(paid_mau_overall_lw)/ nullIf(sum(cumulative_paid_members_lw),
        0) AS PaidUserMAULW,
         sum(paid_mau_overall_ly_chart)/ nullIf(sum(cumulative_paid_members_ly),
        0) AS PaidUserMAULY,
         sum(paid_mau_overall_lylq)/ nullIf(sum(cumulative_paid_members_lylq),
        0) AS PaidUserMAULYLQ,
		/** Week 00 WAU Rate **/
         sum(overall_week_00_actual) / nullIf( sum(total_paid_members_actual),
        0) AS Week0WAURateActual,
         sum(overall_week_00_lq) / nullIf( sum(total_paid_members_lq),
        0) AS Week0WAURateLQ,
         sum(overall_week_00_ly) / nullIf( sum(total_paid_members_ly),
        0) AS Week0WAURateLY,
         sum(overall_week_00_lylq)/ nullIf( sum(total_paid_members_lylq),
        0) AS Week0WAURateLYLQ,
         --sum(overall_week_00_cw) / nullIf( sum(total_paid_members_cw),        0) AS Week0WAURateCW 
		--sum(overall_week_00_lw) / nullIf( sum(total_paid_members_lw),        0) AS Week0WAURateLW 
		/** Week 4 WAU Rate **/
		sum(overall_week_04_actual) / nullIf( sum(total_paid_members_actual),
        0) AS Week04WAURateActual,
         sum(overall_week_04_lq_chart) / nullIf( sum(total_paid_members_lq),
        0) AS Week04WAURateLQ,
         sum(overall_week_04_ly) / nullIf( sum(total_paid_members_ly),
        0) AS Week04WAURateLY,
         sum(overall_week_04_lylq)/ nullIf( sum(total_paid_members_lylq),
        0) AS Week04WAURateLYLQ
FROM newJourn
GROUP BY  channel, geo_code ,market_area_code ,
		case 	when market_area_code = 'US' then 'US' 
					when market_area_code = 'UK' then 'UK'
					when market_area_code = 'GER' then 'GER'
					when market_area_code = 'ANZ' then 'ANZ'
					when market_area_code = 'JPN' then 'JPN'
					else 'ROW'
		end, product_name ,quarter,route_to_market ,segment_pivot , signup_category , subscription_offering ,visit_type ,week 


--JourneyG5ARR : Bounce Rate, Orders, Traffic Conversion, D2P Units, Traffic, Marketing Sourced ARR, Paid Mau Repeat  OVerall Actual, 
--               Cumulative PAid Member, Traffic, Traffic All
SELECT channel,
         geo_code ,
         market_area_code ,
		case 	when market_area_code = 'US' then 'US' 
					when market_area_code = 'UK' then 'UK'
					when market_area_code = 'GER' then 'GER'
					when market_area_code = 'ANZ' then 'ANZ'
					when market_area_code = 'JPN' then 'JPN'
					else 'ROW'
		end as market_area_group,
         product_name ,
         quarter,
         route_to_market ,
         segment_pivot ,
         signup_category ,
         subscription_offering ,
         visit_type ,
         week,
		 /** Conversion TODO GET DATA **/
		 /** Repeat User MAU **/
         sum(paid_mau_repeat_overall_actual) / nullIf(sum( cumulative_paid_members_Actual),
        0) AS RepeatUserMAUActual,
         sum(paid_mau_repeat_overall_CW) / nullIf(sum( cumulative_paid_members_CW),
        0) AS RepeatUserMAUCW,
         sum(paid_mau_repeat_overall_LQ) / nullIf(sum( cumulative_paid_members_LQ),
        0) AS RepeatUserMAULQ,
         sum(paid_mau_repeat_overall_LW) / nullIf(sum( cumulative_paid_members_LW),
        0) AS RepeatUserMAULW,
         sum(paid_mau_repeat_overall_LY) / nullIf(sum( cumulative_paid_members_LY),
        0) AS RepeatUserMAULY,
         sum(paid_mau_repeat_overall_LYLQ) / nullIf(sum( cumulative_paid_members_LYLQ),
        0) AS RepeatUserMAULYLQ,
         sum(paid_mau_repeat_overall_Target) / nullIf(sum( cumulative_paid_members_Target),
        0) AS RepeatUserMAUTarget,
         sum(paid_mau_repeat_overall_Target_CW) / nullIf(sum( cumulative_paid_members_Target_CW),
        0) AS RepeatUserMAUTargetCW,
         sum(paid_mau_repeat_overall_Target_FQ) / nullIf(sum( cumulative_paid_members_Target_FQ),
        0) AS RepeatUserMAUTargetFQ,
		/** Traffic **/
         sum(traffic_actual) AS TrafficActual,
         sum(traffic_cw) AS TrafficCW,
         sum(traffic_lq) AS TrafficLQ,
         sum(traffic_lw) AS TrafficLW,
         sum(traffic_ly) AS TrafficLY,
         sum(traffic_lylq) AS TrafficLYLQ,
         sum(traffic_target) AS TrafficTarget,
         sum(traffic_target_cw) AS TrafficTargetCW,
         sum(traffic_target_fq) AS TrafficTargetFQ,
         (sum(traffic_actual) - sum(traffic_lylq)) / nullIf(sum(traffic_lylq),
        0) AS TrafficQQLY,
         (sum(traffic_actual) - sum(traffic_lq)) / nullIf(sum(traffic_lq),
        0) AS TrafficQQTY,
         (sum(traffic_actual) - sum(traffic_target)) / nullIf(sum(traffic_ly),
        0) AS TrafficVsQrf,
         (sum(traffic_cw) - sum(traffic_target_cw)) / nullIf(sum(traffic_ly),
        0) AS TrafficVsQrfCW,
         (sum(traffic_actual) - sum(traffic_target))as TrafficVsQrfDiff,
         (sum(traffic_CW) - sum(traffic_target_cw)) AS TrafficVsQrfDiffCW,
         (sum(traffic_cw) - sum(traffic_lw)) / nullIf(sum(traffic_lw),
        0) AS TrafficWW,
         (sum(traffic_actual) - sum(traffic_ly)) / nullIf(sum(traffic_ly),
        0) AS TrafficYY,
		/** Bouncing Rate **/
         sum(bounce_rate_base_actual)  BounceRateActual,
         sum(bounce_rate_base_cw)  BounceRateCW,
         sum(bounce_rate_base_lw) BounceRateLW,
         sum(bounce_rate_base_ly)  BounceRateLY,
         sum(bounce_rate_base_lq)  BounceRateLQ,
         sum(bounce_rate_base_lylq) AS BounceRateLYLQ,
        /*Entries*/
          sum(entries_actual) AS EntriesActual,
         sum(entries_cw) AS EntriesCW,
         sum(entries_lq) AS EntriesLQ,
         sum(entries_lw) AS EntriesLW,
         sum(entries_lylq) AS EntriesLYLQ,
         sum(entries_ly) AS EntriesLY,
         sum(entries_target_fq) AS EntriesTargetFQ,
         sum(entries_vs_qrf_diff_cw) AS EntriesVsQrfDiffCW,
         sum(entries_vs_qrf_diff) AS EntriesVsQrfDiff
FROM newJourn
GROUP BY  channel, geo_code ,market_area_code ,
		case 	when market_area_code = 'US' then 'US' 
					when market_area_code = 'UK' then 'UK'
					when market_area_code = 'GER' then 'GER'
					when market_area_code = 'ANZ' then 'ANZ'
					when market_area_code = 'JPN' then 'JPN'
					else 'ROW'
		end, product_name ,quarter,route_to_market ,segment_pivot , signup_category , subscription_offering ,visit_type ,week 

--JourneyG6ARR :F2P Conversion
SELECT channel,
         geo_code ,
         market_area_code ,
		case 	when market_area_code = 'US' then 'US' 
					when market_area_code = 'UK' then 'UK'
					when market_area_code = 'GER' then 'GER'
					when market_area_code = 'ANZ' then 'ANZ'
					when market_area_code = 'JPN' then 'JPN'
					else 'ROW'
		end as market_area_group,
         product_name ,
         quarter,
         route_to_market ,
         segment_pivot ,
         signup_category ,
         subscription_offering ,
         visit_type ,
         week,
		 /** F2P Conversions **/
         sum(f2p_units_lq) / nullIf(sum(cumulative_qfms_lq),
        0) AS F2PConversionLQ,
         sum(f2p_units_ly) / nullIf(sum(cumulative_qfms_ly),
        0) AS F2PConversionLY,
         --sum(f2p_units_lw) / nullIf(cumulative_qfms_lw,         0) AS F2PConversionLW,
         sum(f2p_units_lylq) / nullIf(sum(cumulative_qfms_lylq),
        0) AS F2PConversionLYLQ,
         sum(f2p_units_actual) / nullIf(sum(cumulative_qfms_actual),
        0) AS F2PConversionActual 
		--sum(f2p_units_cw) / nullIf(sum(cumulative_qfms_cw),         0) AS F2PConversion
FROM newJourn
GROUP BY  channel, geo_code ,market_area_code ,
		case 	when market_area_code = 'US' then 'US' 
					when market_area_code = 'UK' then 'UK'
					when market_area_code = 'GER' then 'GER'
					when market_area_code = 'ANZ' then 'ANZ'
					when market_area_code = 'JPN' then 'JPN'
					else 'ROW'
		end, product_name ,quarter,route_to_market ,segment_pivot , signup_category , subscription_offering ,visit_type ,week

--JourneyG9ARR : D2p Conversion, Marketing Soured ARR
SELECT channel,
         geo_code ,
         market_area_code ,
		case 	when market_area_code = 'US' then 'US' 
					when market_area_code = 'UK' then 'UK'
					when market_area_code = 'GER' then 'GER'
					when market_area_code = 'ANZ' then 'ANZ'
					when market_area_code = 'JPN' then 'JPN'
					else 'ROW'
		end as market_area_group,
         product_name ,
         quarter,
         route_to_market ,
         segment_pivot ,
         signup_category ,
         subscription_offering ,
         visit_type ,
         week,
         /**D2p Conversion**/ 
		 sum(d2p_units_lq)/ nullIf(sum(traffic_lq),
        0) AS D2PConversionLQ,
         sum(d2p_units_ly)/ nullIf(sum(traffic_ly),
        0) AS D2PConversionLY,
         sum(d2p_units_lylq)/ nullIf(sum(traffic_lylq),
        0) AS D2PConversionLYLQ,
         sum(d2p_units_actual)/ nullIf(sum(traffic_actual),
        0) AS D2PConversionActual,
         sum(d2p_units_cw)/ nullIf(sum(traffic_cw),
        0) AS D2PConversionCW,
         sum(d2p_units_lw)/ nullIf(sum(traffic_lw),
        0) AS D2PConversionLW,
         /**Marketing Sourced ARR**/ 
		 sum(marketing_sourced_arr_actual) AS MarketingSourcedARRActual,
         sum(marketing_sourced_arr_cw) AS MarketingSourcedARRCW,
         sum(marketing_sourced_arr_ly) AS MarketingSourcedARRLY,
         sum(marketing_sourced_arr_lq) AS MarketingSourcedARRLQ,
         sum(marketing_sourced_arr_lw) AS MarketingSourcedARRLW,
         sum(marketing_sourced_arr_lylq) AS MarketingSourcedARRLYLQ,
         sum(marketing_sourced_arr_target) AS MarketingSourcedARRTarget,
         sum(marketing_sourced_arr_target_cw) AS MarketingSourcedARRTargetCW,
         sum(marketing_sourced_arr_target_fq) AS MarketingSourcedARRTargetFQ,
         (sum(marketing_sourced_arr_actual) - sum(marketing_sourced_arr_lylq)) / nullIf(sum(marketing_sourced_arr_lylq),
         0) AS MarketingSourcedARRQQLY,
         (sum(marketing_sourced_arr_actual) - sum(marketing_sourced_arr_lq)) / nullIf(sum(marketing_sourced_arr_lq),
         0) AS MarketingSourcedARRQQTY,
         (sum(marketing_sourced_arr_actual) - sum(marketing_sourced_arr_target)) / nullIf(sum(marketing_sourced_arr_target),
         0) AS MarketingSourcedARRVsQrf,
         (sum(marketing_sourced_arr_cw) - sum(marketing_sourced_arr_target_cw)) / nullIf(sum(marketing_sourced_arr_target_cw),
         0) AS MarketingSourcedARRVsQrfCW,
         (sum(marketing_sourced_arr_actual) - sum(marketing_sourced_arr_target))as MarketingSourcedARRVsQrfDiff,
         (sum(marketing_sourced_arr_cw) - sum(marketing_sourced_arr_target_cw)) AS MarketingSourcedARRVsQrfDiffCW,
         (sum(marketing_sourced_arr_cw) - sum(marketing_sourced_arr_lw)) / nullIf(sum(marketing_sourced_arr_lw),
         0) AS MarketingSourcedARRWW,
         (sum(marketing_sourced_arr_actual) - sum(marketing_sourced_arr_ly)) / nullIf(sum(marketing_sourced_arr_ly),
         0) AS MarketingSourcedARRYY
FROM newJourn
GROUP BY  channel, geo_code ,market_area_code ,
		case 	when market_area_code = 'US' then 'US' 
					when market_area_code = 'UK' then 'UK'
					when market_area_code = 'GER' then 'GER'
					when market_area_code = 'ANZ' then 'ANZ'
					when market_area_code = 'JPN' then 'JPN'
					else 'ROW'
		end, product_name ,quarter,route_to_market ,segment_pivot , signup_category , subscription_offering ,visit_type ,week 

/*************** Every Row Selected ********/
SELECT channel,
         geo_code ,
         market_area_code ,
		case 	when market_area_code = 'US' then 'US' 
					when market_area_code = 'UK' then 'UK'
					when market_area_code = 'GER' then 'GER'
					when market_area_code = 'ANZ' then 'ANZ'
					when market_area_code = 'JPN' then 'JPN'
					else 'ROW'
		end as market_area_group,
         product_name ,
         quarter,
         route_to_market ,
         segment_pivot ,
         signup_category ,
         subscription_offering ,
         visit_type ,
         week,
         sum([28day_new_uqfm_to_qfm_base_actual]) AS Day28NewUQFMActual ,
         sum([28day_new_uqfm_to_qfm_base_cw]) AS Day28NewUQFMCW ,
         sum([28day_new_uqfm_to_qfm_base_lq]) AS Day28NewUQFMLQ ,
         sum([28day_new_uqfm_to_qfm_base_lw]) AS Day28NewUQFMLW ,
         sum([28day_new_uqfm_to_qfm_base_lylq]) AS Day28NewUQFMLYLQ ,
         sum([28day_new_uqfm_to_qfm_base_ly]) AS Day28NewUQFMLY ,
         sum([28day_new_uqfm_to_qfm_base_target_cw]) AS Day28NewUQFMTargetCW ,
         sum([28day_new_uqfm_to_qfm_base_target_fq]) AS Day28NewUQFMTargetFQ ,
         sum([28day_new_uqfm_to_qfm_base_target]) AS Day28NewUQFMTarget ,
         sum([28day_new_uqfm_to_qfm_base_vs_qrf_diff_cw]) AS Day28NewUQFMVsQrfDiffCW ,
         sum([28day_new_uqfm_to_qfm_base_vs_qrf_diff]) AS Day28NewUQFMVsQrfDiff ,
         sum(bounce_rate_base_actual) AS BounceRateActual ,
         sum(bounce_rate_base_cw) AS BounceRateCW ,
         sum(bounce_rate_base_lq) AS BounceRateLQ ,
         sum(bounce_rate_base_lw) AS BounceRateLW ,
         sum(bounce_rate_base_lylq) AS BounceRateLYLQ ,
         sum(bounce_rate_base_ly) AS BounceRateLY ,
         /**/ sum(cumulative_paid_members_actual_chart) AS CumulativePaidMembersActualChart,
         sum(cumulative_paid_members_cw) AS CumulativePaidMembersActual,
         sum(cumulative_paid_members_lq_chart) AS CumulativePaidMembersLQChart,
         sum(cumulative_paid_members_lq) AS CumulativePaidMembersLQ,
         sum(cumulative_paid_members_lw) AS CumulativePaidMembersLW,
         sum(cumulative_paid_members_ly_chart) AS CumulativePaidMembersLYChart,
         sum(cumulative_paid_members_lylq_chart) AS CumulativePaidMembersLYLQChart,
         sum(cumulative_paid_members_lylq) AS CumulativePaidMembersLYLQ,
         sum(cumulative_paid_members_ly) AS LY,
         sum(cumulative_paid_members_target_chart) AS CumulativePaidMembersTargetChart,
         sum(cumulative_paid_members_target_cw) AS CumulativePaidMembersTargetCW,
         sum(cumulative_paid_members_target_fq) AS CumulativePaidMembersTargetFQ,
         sum(cumulative_paid_members_target) AS CumulativePaidMembersTarget,
         /**/ sum(cumulative_qfms_actual_chart) AS CumulativeQFMSActualChart,
         sum(cumulative_qfms_actual) AS CumulativeQFMSActual,
         sum(cumulative_qfms_lq_chart) AS CumulativeQFMSLQChart,
         sum(cumulative_qfms_lq) AS CumulativeQFMSLQ,
         sum(cumulative_qfms_ly_chart) AS CumulativeQFMSLYChart,
         sum(cumulative_qfms_lylq_chart) AS CumulativeQFMSLYLQChart,
         sum(cumulative_qfms_lylq) AS CumulativeQFMSLYLQ,
         sum(cumulative_qfms_ly) AS CumulativeQFMSLY,
         sum(cumulative_qfms_target_chart) AS CumulativeQFMSTargetChart,
         sum(cumulative_qfms_target_cw) AS CumulativeQFMSTargetCW,
         sum(cumulative_qfms_target_fq) AS CumulativeQFMSTargetFQ,
         sum(cumulative_qfms_target) AS CumulativeQFMSTarget,
         /**/ sum(cumulative_uqfms_actual_chart) AS CumulativeUqfmsActualChart,
         sum(cumulative_uqfms_actual) AS CumulativeUqfmsActual,
         sum(cumulative_uqfms_lq_chart) AS CumulativeUqfmsLQChart,
         sum(cumulative_uqfms_lq) AS CumulativeUqfmsLQ,
         sum(cumulative_uqfms_ly_chart) AS CumulativeUqfmsLYChart,
         sum(cumulative_uqfms_lylq_chart) AS CumulativeUqfmsLYLQChart,
         sum(cumulative_uqfms_lylq) AS CumulativeUqfmsLYLQ,
         sum(cumulative_uqfms_ly) AS CumulativeUqfmsLY,
         sum(cumulative_uqfms_target_chart) AS CumulativeUqfmsTargetChart,
         sum(cumulative_uqfms_target_cw) AS CumulativeUqfmsTargetCW,
         sum(cumulative_uqfms_target_fq) AS CumulativeUqfmsTargetFQ,
         sum(cumulative_uqfms_target) AS CumulativeUqfmsTarget,
         /**/ sum(d2p_units_actual) AS D2PUnitsActual,
         sum(d2p_units_cw) AS D2PUnitsCW,
         sum(d2p_units_lq) AS D2PUnitsLQ,
         sum(d2p_units_lw) AS D2PUnitsLW,
         sum(d2p_units_lylq) AS D2PUnitsLYLQ,
         sum(d2p_units_ly) AS D2PUnitsLY,
         /**/ sum(engagement_index_actual_chart) AS EngagmentIndexActualChart,
         sum(engagement_index_actual) AS EngagmentIndexActual,
         sum(engagement_index_base_cw) AS EngagmentIndexCW,
         sum(engagement_index_base_lw) AS EngagmentIndexLW,
         sum(engagement_index_lq_chart) AS EngagmentIndexLQChart,
         sum(engagement_index_lq) AS EngagmentIndexLQ,
         sum(engagement_index_ly_chart) AS EngagmentIndexLYChart,
         sum(engagement_index_lylq_chart) AS EngagmentIndexLYLQChart,
         sum(engagement_index_lylq) AS EngagmentIndexLYLQ,
         sum(engagement_index_ly) AS EngagmentIndexLY,
         /**/ sum(entries_actual) AS EntriesActual,
         sum(entries_cw) AS EntriesCW,
         sum(entries_lq) AS EntriesLQ,
         sum(entries_lw) AS EntriesLW,
         sum(entries_lylq) AS EntriesLYLQ,
         sum(entries_ly) AS EntriesLY,
         sum(entries_target_fq) AS EntriesTargetFQ,
         sum(entries_vs_qrf_diff_cw) AS EntriesVsQrfDiffCW,
         sum(entries_vs_qrf_diff) AS EntriesVsQrfDiff,
         /**/ sum(f2p_units_actual) AS F2PUnitsActual,
         sum(f2p_units_cw) AS F2PUnitsCW,
         sum(f2p_units_lq) AS F2PUnitsLQ,
         sum(f2p_units_lw) AS F2PUnitsLW,
         sum(f2p_units_lylq) AS F2PUnitsLYLQ,
         sum(f2p_units_ly) AS F2PUnitsLY,
         /**/ sum(learn_panel_30_days_actual_chart) AS LearnPanel30DaysActualChart,
         sum(learn_panel_30_days_actual) AS LearnPanel30DaysActual,
         sum(learn_panel_30_days_cw) AS LearnPanel30DaysCW,
         sum(learn_panel_30_days_lq_chart) AS LearnPanel30DaysLQChart,
         sum(learn_panel_30_days_lq) AS LearnPanel30DaysLQ,
         sum(learn_panel_30_days_lw) AS LearnPanel30DaysLW,
         sum(learn_panel_30_days_ly_chart) AS LearnPanel30DaysLYChart,
         sum(learn_panel_30_days_lylq_chart) AS LearnPanel30DaysLYLQChart,
         sum(learn_panel_30_days_lylq) AS LearnPanel30DaysLYLQ,
         sum(learn_panel_30_days_ly) AS LearnPanel30DaysLY,
         sum(learn_panel_30_days_target_chart) AS LearnPanel30DaysTargetChart,
         sum(learn_panel_30_days_target_cw) AS LearnPanel30DaysTargetCW,
         sum(learn_panel_30_days_target) AS LearnPanel30DaysTarget,
         /**/ sum(marketable_universe_actual) AS MarketableUniverseActual,
         sum(marketable_universe_cw) AS MarketableUniverseCW,
         sum(marketable_universe_lq) AS MarketableUniverseLQ,
         sum(marketable_universe_lw) AS MarketableUniverseLW,
         sum(marketable_universe_lylq) AS MarketableUniverseLYLQ,
         sum(marketable_universe_ly) AS MarketableUniverseLY,
         sum(marketable_universe_target_cw) AS MarketableUniverseTargetCW,
         sum(marketable_universe_target_fq) AS MarketableUniverseTargetFQ ,
         sum(marketable_universe_target) AS MarketableUniverseTarget,
         sum(marketable_universe_vs_qrf_cw) AS MarketableUniverseVsQrfDiffCW,
         sum(marketable_universe_vs_qrf_diff) AS MarketableUniverseVsQrfDiff,
         /**/ sum(marketing_sourced_arr_actual) AS MarketingSourcedARRActual,
         sum(marketing_sourced_arr_cw) AS MarketingSourcedARRCW,
         sum(marketing_sourced_arr_lq) AS MarketingSourcedARRLQ,
         sum(marketing_sourced_arr_lw) AS MarketingSourcedARRLW,
         sum(marketing_sourced_arr_lylq) AS MarketingSourcedARRLYLQ,
         sum(marketing_sourced_arr_ly) AS MarketingSourcedARRLY,
         sum(marketing_sourced_arr_target_cw) AS MarketingSourcedARRTargetCW,
         sum(marketing_sourced_arr_target_fq) AS MarketingSourcedARRTargetFQ,
         sum(marketing_sourced_arr_target) AS MarketingSourcedARRTarget,
         sum(marketing_sourced_arr_vs_qrf_diff_cw) AS MarketingSourcedARRVsQrfDiffCW,
         sum(marketing_sourced_arr_vs_qrf_diff) AS MarketingSourcedARRVsQrfDiff ,
         /**/ sum(members_actual_chart) AS MembersActualChart,
         sum(members_actual) AS MembersActual,
         sum(members_cw) AS MembersCW,
         sum(members_lq_chart) AS MembersLQChart,
         sum(members_lq) AS MembersLQ,
         sum(members_lw) AS MembersLW,
         sum(members_ly_chart) AS MembersLYChart,
         sum(members_lylq_chart) AS MembersLYLQChart,
         sum(members_lylq) AS MembersLYLQ,
         sum(members_ly) AS MembersLY,
         /**/ sum(new_qfms_28_actual) AS NewQFMS28Actual,
         sum(new_qfms_28_lq) AS NewQFMS28LQ,
         sum(new_qfms_28_lylq) asNewQFMS28LYLQ ,
         sum(new_qfms_28_ly) AS NewQFMS28LY,
         sum(new_qfms_28_target) AS NewQFMS28Target,
         /**/ sum(new_qfms_actual) AS NewQFMSActual,
         sum(new_qfms_cw) AS NewQFMSCW,
         sum(new_qfms_lq) AS NewQFMSLQ,
         sum(new_qfms_lw) AS NewQFMSLW,
         sum(new_qfms_lylq) AS NewQFMSLYLQ,
         sum(new_qfms_ly) AS NewQFMSLY,
         sum(new_qfms_target_cw) AS NewQFMSTargetCW,
         sum(new_qfms_target_fq) AS NewQFMSTargetFQ,
         sum(new_qfms_target) AS NewQFMSTarget,
         sum(new_qfms_vs_qrf_cw_diff) AS NewQFMSVsQrfDiffCW,
         sum(new_qfms_vs_qrf_diff) AS NewQFMSVsQrfDiff,
         /**/ sum(new_uqfms_actual) AS NewUQFMSActual,
         sum(new_uqfms_cw) AS NewUQFMSCW,
         sum(new_uqfms_lq) AS NewUQFMSLQ,
         sum(new_uqfms_lw) AS NewUQFMSLW,
         sum(new_uqfms_lylq) AS NewUQFMSLYLQ,
         sum(new_uqfms_ly) AS NewUQFMSLY,
         sum(new_uqfms_target_cw) AS NewUQFMSTargetCW,
         sum(new_uqfms_target_fq) AS NewUQFMSTargetFQ ,
         sum(new_uqfms_target) AS NewUQFMSTarget,
         sum(new_uqfms_vs_qrf_cw_diff) AS NewUQFMSVsQrfDiffCW,
         sum(new_uqfms_vs_qrf_diff) AS NewUQFMSVsQrfDiff,
         /**/ sum(orders_actual) AS OrdersActual,
         sum(orders_cw) AS OrdersCW,
         sum(orders_lq) AS OrdersLQ,
         sum(orders_lw) AS OrdersLW,
         sum(orders_lylq) AS OrdersLYLQ,
         sum(orders_ly) AS OrdersLY,
         sum(orders_target_cw) AS OrdersTargetCW,
         sum(orders_target_fq) AS OrdersTargetFQ,
         sum(orders_target) AS OrdersTarget,
         sum(orders_vs_qrf_cw_diff) AS OrdersVsQrfDiffCW,
         sum(orders_vs_qrf_diff) AS OrdersVsQrfDiff,
         /**/ sum(overall_week_00_actual_chart) AS OverallWeek00ActualChart,
         sum(overall_week_00_actual) AS OverallWeek00Actual,
         sum(overall_week_00_cw) AS OverallWeek00CW,
         sum(overall_week_00_lq_chart) AS OverallWeek00LQChart,
         sum(overall_week_00_lq) AS OverallWeek00LQ,
         sum(overall_week_00_lw) AS OverallWeek00LW,
         sum(overall_week_00_ly_chart) AS OverallWeek00LYChart,
         sum(overall_week_00_lylq_chart) AS OverallWeek00LYLQChart,
         sum(overall_week_00_lylq) AS OverallWeek00LYLQ,
         sum(overall_week_00_ly) AS OverallWeek00LY,
         sum(overall_week_00_target_cw) AS OverallWeek00TargetCW,
         sum(overall_week_00_target_fq) AS OverallWeek00TargetFQ,
         sum(overall_week_00_target) AS OverallWeek00Target,
         /**/ sum(overall_week_04_actual_chart) AS OverallWeek04ActualChart,
         sum(overall_week_04_actual) AS OverallWeek04Actual,
         sum(overall_week_04_cw) AS OverallWeek04CW,
         sum(overall_week_04_lq_chart) AS OverallWeek04LQChart,
         sum(overall_week_04_lw) AS OverallWeek04LW,
         sum(overall_week_04_ly_chart) AS OverallWeek04LYChart,
         sum(overall_week_04_lylq_chart) AS OverallWeek04LYLQChart,
         sum(overall_week_04_lylq) asOverallWeek04LYLQ ,
         sum(overall_week_04_ly) AS OverallWeek04LY,
         sum(overall_week_04_target_chart) AS OverallWeek04TargetChart,
         sum(overall_week_04_target_cw) AS OverallWeek04TargetCW,
         sum(overall_week_04_target_fq) AS OverallWeek04TargetFQ ,
         sum(overall_week_04_target) AS OverallWeek04Target,
         /**/ sum(paid_download_7_days_actual_chart) AS PaidDownload7DaysActualChart,
         sum(paid_download_7_days_actual) AS PaidDownload7DaysActual,
         sum(paid_download_7_days_lq_chart) AS PaidDownload7DaysLQChart,
         sum(paid_download_7_days_lq) AS PaidDownload7DaysLQ,
         sum(paid_download_7_days_ly_chart) AS PaidDownload7DaysLYChart,
         sum(paid_download_7_days_lylq_chart) AS PaidDownload7DaysLYLQChart,
         sum(paid_download_7_days_lylq) AS PaidDownload7DaysLYLQ,
         sum(paid_download_7_days_ly) AS PaidDownload7DaysLY,
         sum(paid_download_7_days_target_chart) AS PaidDownload7DaysTargetChart,
         sum(paid_download_7_days_target) AS PaidDownload7DaysTarget,
         /**/ sum(paid_mau_overall_actual_chart) AS PaidMAUOverallActualChart,
         sum(paid_mau_overall_actual) AS PaidMAUOverallActual,
         sum(paid_mau_overall_cw) AS PaidMAUOverallCW ,
         sum(paid_mau_overall_lq_chart) AS PaidMAUOverallLQChart,
         sum(paid_mau_overall_lq) AS PaidMAUOverallLQ,
         sum(paid_mau_overall_lw) AS PaidMAUOverallLW,
         sum(paid_mau_overall_ly_chart) AS PaidMAUOverallLYChart,
         sum(paid_mau_overall_lylq_chart) AS PaidMAUOverallLYLQChart,
         sum(paid_mau_overall_lylq) AS PaidMAUOverallLYLQ,
         /**/ sum(paid_mau_repeat_overall_actual_chart) AS PaidMAURepeatOverallActualChart,
         sum(paid_mau_repeat_overall_actual) AS PaidMAURepeatOverallActual,
         sum(paid_mau_repeat_overall_cw) AS PaidMAURepeatOverallCW,
         sum(paid_mau_repeat_overall_lq_chart) AS PaidMAURepeatOverallLQChart,
         sum(paid_mau_repeat_overall_lq) AS PaidMAURepeatOverallLQ,
         sum(paid_mau_repeat_overall_lw) AS PaidMAURepeatOverallLW,
         sum(paid_mau_repeat_overall_ly_chart) AS PaidMAURepeatOverallLYChart,
         sum(paid_mau_repeat_overall_lylq_chart) AS PaidMAURepeatOverallLYLQChart,
         sum(paid_mau_repeat_overall_lylq) AS PaidMAURepeatOverallLYLQ,
         sum(paid_mau_repeat_overall_ly) AS PaidMAURepeatOverallLY,
         sum(paid_mau_repeat_overall_target_chart) AS PaidMAURepeatOverallTargetChart,
         sum(paid_mau_repeat_overall_target_cw) AS PaidMAURepeatOverallTargetCW,
         sum(paid_mau_repeat_overall_target_fq) AS PaidMAURepeatOverallTargetFQ,
         sum(paid_mau_repeat_overall_target) AS PaidMAURepeatOverallTarget,
         /**/ sum(paid_media_sourced_uqfms_actual) AS PaidMediaSourcedUQFMSActual,
         sum(paid_media_sourced_uqfms_cw) AS PaidMediaSourcedUQFMSCW,
         sum(paid_media_sourced_uqfms_lq) AS PaidMediaSourcedUQFMSLQ,
         sum(paid_media_sourced_uqfms_lw) AS PaidMediaSourcedUQFMSLW,
         sum(paid_media_sourced_uqfms_lylq) AS PaidMediaSourcedUQFMSLYLQ,
         sum(paid_media_sourced_uqfms_ly) AS PaidMediaSourcedUQFMSLY,
         sum(paid_media_sourced_uqfms_target_cw) AS PaidMediaSourcedUQFMSTargetCW,
         sum(paid_media_sourced_uqfms_target_fq) AS PaidMediaSourcedUQFMSTargetFQ,
         sum(paid_media_sourced_uqfms_target) AS PaidMediaSourcedUQFMSTarget,
         sum(paid_media_sourced_uqfms_vs_qrf_cw_diff) AS PaidMediaSourcedUQFMSVsQrfDiffCW,
         sum(paid_media_sourced_uqfms_vs_qrf_diff) AS PaidMediaSourcedUQFMSVsQrfDiff,
         /**/ sum(paid_media_spend_actual) AS PaidMediaSpendActual,
         sum(paid_media_spend_cw) AS PaidMediaSpendCW,
         sum(paid_media_spend_lq) AS PaidMediaSpendLQ,
         sum(paid_media_spend_lw) AS PaidMediaSpendLW,
         sum(paid_media_spend_lylq) AS PaidMediaSpendLYLQ,
         sum(paid_media_spend_ly) AS PaidMediaSpendLY,
         sum(paid_media_spend_target_cw) AS PaidMediaSpendTargetCW ,
         sum(paid_media_spend_target_fq) AS PaidMediaSpendTargetFQ,
         sum(paid_media_spend_target) AS PaidMediaSpendTarget,
         sum(paid_media_spend_vs_qrf_cw_diff) AS PaidMediaSpendVsQrfDiffCW,
         sum(paid_media_spend_vs_qrf_diff) AS PaidMediaSpendVsQrfDiff,
         /**/ sum(total_paid_members_actual_chart) AS TotalPaidMembersActualChart,
         sum(total_paid_members_actual) AS TotalPaidMembersActual,
         sum(total_paid_members_lq_chart) AS TotalPaidMembersLQChart ,
         sum(total_paid_members_lq) AS TotalPaidMembersLQ,
         sum(total_paid_members_ly_chart) AS TotalPaidMembersLYChart,
         sum(total_paid_members_lylq_chart) AS TotalPaidMembersLYLQChart,
         sum(total_paid_members_lylq) AS TotalPaidMembersLYLQ,
         sum(total_paid_members_ly) AS TotalPaidMembersLY,
         sum(total_paid_members_target_chart) AS TotalPaidMembersTargetChart,
         sum(total_paid_members_target) AS TotalPaidMembersTarget,
         /**/ sum(traffic_actual) AS TrafficActual,
         sum(traffic_all_actual) AS TrafficAllActual,
         sum(traffic_cw) AS TrafficCW,
         sum(traffic_all_cw) AS TrafficAllCW,
         sum(traffic_lq) AS TrafficLQ,
         sum(traffic_all_lq) AS TrafficAllLQ,
         sum(traffic_lw) AS TrafficLW,
         sum(traffic_all_lw) AS TrafficAllLW,
         sum(traffic_ly) AS TrafficLY,
         sum(traffic_lylq) AS TrafficLYLQ,
         sum(traffic_all_lylq) AS TrafficAllLYLQ,
         sum(traffic_all_ly) AS TrafficAllLY,
         sum(traffic_target) AS TrafficTarget,
         sum(traffic_target_cw) AS TrafficTargetCW,
         sum(traffic_all_target_cw) AS TrafficAllTargetCWC,
         sum(traffic_target_fq) AS TrafficTargetFQ,
         sum(traffic_all_target_fq) AS TrafficAllTargetFQ,
         sum(traffic_all_target) AS TrafficAllTarget,
         sum(traffic_vs_qrf_cw) AS TrafficVsQrfCW,
         sum(traffic_vs_qrf_cw_diff) AS TrafficVsQrfDiffCW,
         sum(traffic_all_vs_qrf_cw_diff) AS TrafficAllVsQrfDiffCW,
         sum(traffic_all_vs_qrf_cw) AS TrafficAllVsQrfCW,
         sum(traffic_vs_qrf_diff) AS TrafficVsQrfDiff,
         sum(traffic_all_vs_qrf_diff) AS TrafficAllVsQrfDiff,
         /**/ sum(uqfm_denom_actual) AS UQFMDenomActual ,
         sum(uqfm_denom_cw) AS UQFMDenomCW,
         sum(uqfm_denom_lq) AS UQFMDenomLQ,
         sum(uqfm_denom_lw) AS UQFMDenomLW,
         sum(uqfm_denom_lylq) AS UQFMDenomLYLQ,
         sum(uqfm_denom_ly) AS UQFMDenomLY,
         sum(uqfm_nom_actual) AS UQFMNOMActual,
         sum(uqfm_nom_cw) AS UQFMNOMCW,
         sum(uqfm_nom_lq) AS UQFMNOMLQ,
         sum(uqfm_nom_lw) AS UQFMNOMLW,
         sum(uqfm_nom_lylq) AS UQFMNOMLYLQ,
         sum(uqfm_nom_ly) AS UQFMNOMLY
FROM newJourn
GROUP BY  channel, geo_code ,market_area_code ,
		case 	when market_area_code = 'US' then 'US' 
					when market_area_code = 'UK' then 'UK'
					when market_area_code = 'GER' then 'GER'
					when market_area_code = 'ANZ' then 'ANZ'
					when market_area_code = 'JPN' then 'JPN'
					else 'ROW'
		end, product_name ,quarter,route_to_market ,segment_pivot , signup_category , subscription_offering ,visit_type ,week;