BuyActualTargetPrimary
BuyActualTargetSecondary
BuyMultichart
BuyQTDTotal
BuyGeoQTD
BuyMarketQTD
BuyWebSegmentQTD
BuyChannelQTD

ConversionActualTargetPrimary
ConversionActualTargetSecondary
ConversionMultichart
ConversionQTDTotal
ConversionGeoQTD
ConversionMarketQTD
ConversionWebSegmentQTD
ConversionChannelQTD

PaidMediaSpendActualTargetPrimary
PaidMediaSpendActualTargetSecondary
PaidMediaSpendMultichart
PaidMediaSpendQTDTotal
PaidMediaSpendGeoQTD
PaidMediaSpendMarketQTD
PaidMediaSpendWebSegmentQTD
PaidMediaSpendChannelQTD

MarketingSourcedARRActualTargetPrimary
MarketingSourcedARRActualTargetSecondary
MarketingSourcedARRMultichart
MarketingSourcedARRQTDTotal
MarketingSourcedARRGeoQTD
MarketingSourcedARRMarketQTD
MarketingSourcedARRWebSegmentQTD
MarketingSourcedARRChannelQTD

GrossNewARRActualTargetPrimary
GrossNewARRActualTargetSecondary
GrossNewARRMultichart
GrossNewARRQTDTotal
GrossNewARRGeoQTD
GrossNewARRMarketQTD
GrossNewARRWebSegmentQTD
GrossNewARRChannelQTD

GrossNewUnitsActualTargetPrimary
GrossNewUnitsActualTargetSecondary
GrossNewUnitsMultichart
GrossNewUnitsQTDTotal
GrossNewUnitsGeoQTD
GrossNewUnitsMarketQTD
GrossNewUnitsWebSegmentQTD
GrossNewUnitsChannelQTD
