--DiscoverActualTargetPrimary
--DiscoverActualTargetSecondary
--DiscoverMultichart
--DiscoverQTDTotal
--DiscoverGeoQTD
--DiscoverMarketQTD
--DiscoverWebSegmentQTD
--DiscoverChannelQTD

--TrafficActualTargetPrimary
--TrafficActualTargetSecondary
--TrafficMultichart
--TrafficQTDTotal
--TrafficGeoQTD
--TrafficMarketQTD
--TrafficWebSegmentQTD
--TrafficChannelQTD

--MarketableUniverseActualTargetPrimary
--MarketableUniverseActualTargetSecondary
--MarketableUniverseMultichart
--MarketableUniverseQTDTotal
--MarketableUniverseGeoQTD
--MarketableUniverseMarketQTD
--MarketableUniverseWebSegmentQTD
--MarketableUniverseChannelQTD

--PaidMediaSpendActualTargetPrimary
--PaidMediaSpendActualTargetSecondary
--PaidMediaSpendMultichart
--PaidMediaSpendQTDTotal
--PaidMediaSpendGeoQTD
--PaidMediaSpendMarketQTD
--PaidMediaSpendWebSegmentQTD
--PaidMediaSpendChannelQTD

--PaidMediaSourcedActualTargetPrimary
--PaidMediaSourcedActualTargetSecondary
--PaidMediaSourcedMultichart
--PaidMediaSourcedQTDTotal
--PaidMediaSourcedGeoQTD
--PaidMediaSourcedMarketQTD
--PaidMediaSourcedWebSegmentQTD
--PaidMediaSourcedChannelQTD

--NewUQFMActualTargetPrimary
--NewUQFMActualTargetSecondary
--NewUQFMMultichart
--NewUQFMQTDTotal
--NewUQFMGeoQTD
--NewUQFMMarketQTD
--NewUQFMWebSegmentQTD
--NewUQFMChannelQTD

--BounceRateActualTargetPrimary
--BounceRateActualTargetSecondary
--BounceRateMultichart
--BounceRateQTDTotal
--BounceRateGeoQTD
--BounceRateMarketQTD
--BounceRateWebSegmentQTD
--BounceRateChannelQTD